create table if not exists content (
    id bigint generated by default as identity primary key,
    title text not null unique,
    content_type text not null check (content_type in ('movie', 'tv')),
    genre text[] not null default '{}',
    runtime integer,
    poster_url text,
    overview text
);

create table if not exists situation (
    id bigint generated by default as identity primary key,
    name text not null unique check (name in ('식사시간', '운동중', '자기전'))
);

create table if not exists content_situation (
    id bigint generated by default as identity primary key,
    content_id bigint not null references content (id) on delete cascade,
    situation_id bigint not null references situation (id) on delete cascade,
    fit_score integer not null check (fit_score between 0 and 100),
    unique (content_id, situation_id)
);

create table if not exists review_tag (
    id bigint generated by default as identity primary key,
    content_id bigint not null references content (id) on delete cascade,
    tag_name text not null,
    sentiment_score numeric,
    sentiment_label text
);

create index if not exists idx_content_situation_content_id on content_situation (content_id);
create index if not exists idx_content_situation_situation_id on content_situation (situation_id);
create index if not exists idx_review_tag_content_id on review_tag (content_id);

insert into situation (name) values
    ('식사시간'),
    ('운동중'),
    ('자기전')
on conflict (name) do nothing;
