create table if not exists review (
    id bigint generated by default as identity primary key,
    content_id bigint not null references content (id) on delete cascade,
    title text,
    description text,
    created_at timestamptz not null default now()
);

create index if not exists idx_review_content_id on review (content_id);
