create table if not exists user_review (
    id bigint generated by default as identity primary key,
    content_id bigint not null references content (id) on delete cascade,
    nickname text not null default '익명',
    review_text text not null,
    star_rating integer not null check (star_rating between 1 and 5),
    created_at timestamptz not null default now()
);

create index if not exists idx_user_review_content_id on user_review (content_id);
